#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

current_branch=$(git rev-parse --abbrev-ref HEAD)

if [ "$current_branch" = "main" -a -d "/Applications/Raycast.app" ]; then
  open "raycast://confetti"
fi