name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on
env:
  # Setting an environment variable with the value of a configuration variable
  API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
  APPLICATION_ID: ${{secrets.ALGOLIA_APPLICATION_ID}}
  MAIL_CHIMP_API_URL: ${{vars.MAIL_CHIMP_API_URL}}
  GROUP_ID: ${{secrets.GROUP_ID}}
  LINE_ACCESS_TOKEN: ${{secrets.LINE_ACCESS_TOKEN}}
  BASEURL: ${{vars.BASEURL}}

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm install --frozen-lockfile
      - name: generate changelog.json
        if: contains(github.event.head_commit.message, 'CHANGELOG.md')
        run: |
          node scripts/generateChangelog.js
            if [[ -n $(git status -s) ]]; then
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "generate changelog.json"
            git push
          else
            echo "No changes to commit."
          fi
      - name: Build website
        run: npm run build

      # Popular action to deploy to GitHub Pages:
      # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./build
          # The following lines assign commit authorship to the official
          # GH-Actions bot for deploys to `gh-pages` branch:
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # The GH actions bot is used by default if you didn't specify the two fields.
          # You can swap them out with your own user credentials.
          user_name: Jim876633
          user_email: jim30223@gmail.com
          cname: jimhuang.dev
      - name: Run the Docker container
        run: docker run -e APPLICATION_ID -e API_KEY -e "CONFIG=$(cat config.json)" algolia/docsearch-scraper
      - name: Get commit details
        run: |
          COMMIT_FILES=$(git diff --name-only ${{ github.event.before }}..${{ github.sha }})
          echo "AUTHOR_NAME=$(git log --format='%an' -n 1 ${{ github.sha }})" >> $GITHUB_ENV
          for file in $COMMIT_FILES; do
            echo "$file"
            if [[ "$file" == "docs/"* ]]; then
              echo "FILE_PATH=$(echo "$file" | sed 's/\.mdx//')" >> $GITHUB_ENV
            elif [[ "$file" == "blog/"* ]]; then
              echo "FILE_PATH=$(echo "$file" | sed 's/\([0-9]\{4\}\)-\([0-9]\{2\}\)-\([0-9]\{2\}\)-\([^\.]*\)\.\(md\|mdx\)/\/\1\/\2\/\3\/\4/')" >> $GITHUB_ENV
            fi
          done
          echo "Commit Message: ${{ github.event.head_commit.message }}"
          if [[ "${{ github.event.head_commit.message }}" == *feature_blog* ]]; then
            echo "COMMIT_TYPE='Blog'" >> $GITHUB_ENV
          elif [[ "${{ github.event.head_commit.message }}" == *feature_docs* ]]; then
            echo "COMMIT_TYPE='Docs'" >> $GITHUB_ENV
          fi
      - name: Send Line Notification
        run: |
          echo "FILE_PATH: $FILE_PATH"
          echo "COMMIT_TYPE: $COMMIT_TYPE"
          echo "Author: $AUTHOR_NAME"
          if [[ $FILE_PATH && $COMMIT_TYPE ]]; then
            curl -v POST https://api.line.me/v2/bot/message/push \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $LINE_ACCESS_TOKEN" \
            -d "{
                  \"to\": \"$GROUP_ID\",
                  \"messages\": [
                    {
                      \"type\":\"text\",
                      \"text\":\"$AUTHOR_NAME published a $COMMIT_TYPE article, check it out!\n$BASEURL/$FILE_PATH\"
                    }
                  ]
                }"
          fi
